### ISSUE TITLE
Getting exceptions when pushing messages to kafka from JMeter.

### ISSUE THREAD

**Issue by anandcta123** [BrightTag/kafkameter#1]
Hi,

I integrated kafkameter to JMeter. When I try to push messages, I am getting following exception. Please check and let me know, how to resolve these errors.

2015/04/01 10:46:19 INFO  - jmeter.util.BSFTestElement: Registering JMeter version of JavaScript engine as work-round for BSF-22 
2015/04/01 10:46:20 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Cannot find .className property for htmlParser, using default 
2015/04/01 10:46:20 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is  
2015/04/01 10:46:20 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is  
2015/04/01 10:46:20 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is  
2015/04/01 10:46:20 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is  
2015/04/01 10:46:20 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
2015/04/01 10:46:20 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.http.control.gui.WebServiceSamplerGui 
2015/04/01 10:46:20 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.http.modifier.gui.ParamModifierGui 
2015/04/01 10:46:23 INFO  - jorphan.exec.KeyToolUtils: keytool found at 'keytool' 
2015/04/01 10:46:23 INFO  - jmeter.protocol.http.proxy.ProxyControl: HTTP(S) Test Script Recorder SSL Proxy will use keys that support embedded 3rd party resources in file C:\apache-jmeter-2.13\bin\proxyserver.jks 
2015/04/01 10:46:27 INFO  - jmeter.samplers.SampleResult: Note: Sample TimeStamps are START times 
2015/04/01 10:46:27 INFO  - jmeter.samplers.SampleResult: sampleresult.default.encoding is set to ISO-8859-1 
2015/04/01 10:46:27 INFO  - jmeter.samplers.SampleResult: sampleresult.useNanoTime=true 
2015/04/01 10:46:27 INFO  - jmeter.samplers.SampleResult: sampleresult.nanoThreadSleep=5000 
2015/04/01 10:54:56 INFO  - jmeter.services.FileServer: Default base='C:\apache-jmeter-2.13\bin' 
2015/04/01 10:54:56 INFO  - jmeter.gui.action.Load: Loading file: C:\apache-jmeter-2.13\bin\examples\Tagserve-Kafka.jmx 
2015/04/01 10:54:56 INFO  - jmeter.services.FileServer: Set new base='C:\apache-jmeter-2.13\bin\examples' 
2015/04/01 10:54:57 INFO  - jmeter.save.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2 
2015/04/01 10:54:57 INFO  - jmeter.save.SaveService: Using SaveService properties file encoding UTF-8 
2015/04/01 10:54:57 INFO  - jmeter.save.SaveService: Using SaveService properties file version 1656252 
2015/04/01 10:54:57 INFO  - jmeter.save.SaveService: Using SaveService properties version 2.8 
2015/04/01 10:54:57 INFO  - jmeter.save.SaveService: All converter versions present and correct 
2015/04/01 10:54:57 INFO  - jmeter.save.SaveService: Loading file: C:\apache-jmeter-2.13\bin\examples\Tagserve-Kafka.jmx 
2015/04/01 10:54:58 INFO  - jmeter.services.FileServer: Set new base='C:\apache-jmeter-2.13\bin\examples' 
2015/04/01 10:55:11 INFO  - jmeter.engine.StandardJMeterEngine: Listeners will be started after enabling running version 
2015/04/01 10:55:11 INFO  - jmeter.engine.StandardJMeterEngine: To revert to the earlier behaviour, define jmeterengine.startlistenerslater=false 
2015/04/01 10:55:11 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2015/04/01 10:55:11 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2015/04/01 10:55:11 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2015/04/01 10:55:11 INFO  - jmeter.protocol.java.sampler.JavaSampler: Created class: co.signal.kafkameter.KafkaProducerSampler. Uses tearDownTest: false 
2015/04/01 10:55:11 INFO  - jmeter.protocol.java.sampler.JavaSampler: Created class: co.signal.kafkameter.KafkaProducerSampler. Uses tearDownTest: false 
2015/04/01 10:55:11 INFO  - jmeter.protocol.java.sampler.JavaSampler: Created class: co.signal.kafkameter.KafkaProducerSampler. Uses tearDownTest: false 
2015/04/01 10:55:11 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,*local*) 
2015/04/01 10:55:11 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : Kafka Producers 
2015/04/01 10:55:11 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group Kafka Producers. 
2015/04/01 10:55:11 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2015/04/01 10:55:11 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2015/04/01 10:55:11 INFO  - jmeter.threads.JMeterThread: jmeterthread.startearlier=true (see jmeter.properties) 
2015/04/01 10:55:11 INFO  - jmeter.threads.JMeterThread: Running PostProcessors in forward order 
2015/04/01 10:55:11 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2015/04/01 10:55:11 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2015/04/01 10:55:11 INFO  - jmeter.threads.JMeterThread: Thread started: Kafka Producers 1-1 
2015/04/01 10:56:38 ERROR - jmeter.threads.JMeterThread: Error while processing sampler 'Java Request' : java.lang.ArrayIndexOutOfBoundsException: 1
	at kafka.client.ClientUtils$$anonfun$parseBrokerList$1.apply(ClientUtils.scala:102)
	at kafka.client.ClientUtils$$anonfun$parseBrokerList$1.apply(ClientUtils.scala:97)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:57)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:43)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
	at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:43)
	at kafka.client.ClientUtils$.parseBrokerList(ClientUtils.scala:97)
	at kafka.producer.BrokerPartitionInfo.<init>(BrokerPartitionInfo.scala:32)
	at kafka.producer.async.DefaultEventHandler.<init>(DefaultEventHandler.scala:41)
	at kafka.producer.Producer.<init>(Producer.scala:59)
	at kafka.javaapi.producer.Producer.<init>(Producer.scala:26)
	at co.signal.kafkameter.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:91)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:188)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Unknown Source)

2015/04/01 10:56:38 ERROR - jmeter.threads.JMeterThread: Error while processing sampler 'Java Request' : java.lang.ArrayIndexOutOfBoundsException: 1
	at kafka.client.ClientUtils$$anonfun$parseBrokerList$1.apply(ClientUtils.scala:102)
	at kafka.client.ClientUtils$$anonfun$parseBrokerList$1.apply(ClientUtils.scala:97)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:57)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:43)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
	at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:43)
	at kafka.client.ClientUtils$.parseBrokerList(ClientUtils.scala:97)
	at kafka.producer.BrokerPartitionInfo.<init>(BrokerPartitionInfo.scala:32)
	at kafka.producer.async.DefaultEventHandler.<init>(DefaultEventHandler.scala:41)
	at kafka.producer.Producer.<init>(Producer.scala:59)
	at kafka.javaapi.producer.Producer.<init>(Producer.scala:26)
	at co.signal.kafkameter.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:91)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:188)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Unknown Source)

**Comment by codyaray** [comment]
How have you specified the Kafka brokers?

    kafka_brokers: comma-separated list of hosts in the format (hostname:port).

Have you forgotten to include the port?

**Comment by anandcta123** [comment]
Hi I have configured the kafka server.properties by setting advertised ip by setting the machine real IP. Then it is worked fine to send the mesages.

Would you please explain me, how to modify the existing kafka meter to send custom JSON objects of my file or from databse.

I have tried to send the messages through my own file, but it won't send any messages, I got exceptions.

Thanks and regards,
Anand

**Comment by codyaray** [comment]
Hi @anandcta123 

The ["Simplest Possible Example"](https://github.com/BrightTag/kafkameter/blob/master/README.md#simplest-possible-example) section of the README gives instructions for how to write your own Synthetic Load Generator. You just have to implement a method which returns a String for the next message. You could read that from a file or database or any data source you wish.

-Cody

**Comment by anandcta123** [comment]
Hi,

Thanks for the followup. Now I am not having any issues with Kafkameter.
Just a clarification, what is meant by kafka key.

Regards,
Anand

**Comment by codyaray** [comment]
Hi @anandcta123 

Kafka uses a key to partition the messages to different brokers. You can learn more about this by searching for "partition key" in the kafka documentation.

If you don't care how the messages are partitioned (that is, you want them partitioned randomly), then you can use the value of a JMeter Counter as the partition key. Since each message will then have a different key, its effectively randomizing the partition. The sample JMeter Test Plan in Tagserve-Kafka.jmx demonstrates this configuration.

-Cody
