### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException Error

### ISSUE THREAD

**Issue by JCMcRae** [BrightTag/kafkameter#15]
I have installed KafkaMeter by way of the [jMeter Plugins Manager](https://jmeter-plugins.org/), and I have followed the instructions for setting up a test plan and sending a message to a Kafka consumer. But when I run my test, I get this error every time:

```
ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at co.signal.loadgen.LoadGenerator.createGenerator(LoadGenerator.java:70)
	at co.signal.loadgen.LoadGenerator.iterationStart(LoadGenerator.java:57)
	at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:405)
	at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:397)
	at org.apache.jmeter.control.GenericController.next(GenericController.java:158)
	at org.apache.jmeter.control.LoopController.next(LoopController.java:123)
	at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:87)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:247)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at co.signal.loadgen.LoadGenerator.createGenerator(LoadGenerator.java:67)
	... 8 more
Caused by: java.lang.NullPointerException
	at co.signal.loadgen.example.TagserveLoadGenerator.parseSiteWeights(TagserveLoadGenerator.java:121)
	at co.signal.loadgen.example.TagserveLoadGenerator.<init>(TagserveLoadGenerator.java:61)
	... 13 more
```

I am not sure what I am doing wrong, and I am also not certain what I can do to fix this. Could you tell me what the problem may be?

**Comment by codyaray** [comment]
You probably have bad test data based on that result. The TagserveLoadGenerator was just used as an example. The idea is that you write a generator based on your own needs for your use case.
