### ISSUE TITLE
Problems with Jmeter 5.2.1 and Kafka 2.4.0

### ISSUE THREAD

**Issue by santiagomoneta** [BrightTag/kafkameter#26]
Hi!. I just wanted to mention that after updating the pom.xml to update the JMeter and Kafka client versions (5.2.1 and 2.4.0 respectively) adding an extra parameter needed to disable SSL endpoint validation () and compiling... I try to run my JMX from the CLI and get this:

```
2020-03-09 23:14:04,653 INFO o.a.j.u.JMeterUtils: Setting Locale to en_EN
2020-03-09 23:14:04,667 INFO o.a.j.JMeter: Loading user properties from: /usr/local/Cellar/jmeter/5.2.1/libexec/bin/user.properties
2020-03-09 23:14:04,667 INFO o.a.j.JMeter: Loading system properties from: /usr/local/Cellar/jmeter/5.2.1/libexec/bin/system.properties
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: Copyright (c) 1998-2019 The Apache Software Foundation
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: Version 5.2.1
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: java.version=1.8.0_212
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: java.vm.name=OpenJDK 64-Bit Server VM
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: os.name=Mac OS X
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: os.arch=x86_64
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: os.version=10.15.3
2020-03-09 23:14:04,668 INFO o.a.j.JMeter: file.encoding=UTF-8
2020-03-09 23:14:04,669 INFO o.a.j.JMeter: java.awt.headless=true
2020-03-09 23:14:04,669 INFO o.a.j.JMeter: Max memory     =1073741824
2020-03-09 23:14:04,669 INFO o.a.j.JMeter: Available Processors =12
2020-03-09 23:14:04,672 INFO o.a.j.JMeter: Default Locale=English (EN)
2020-03-09 23:14:04,672 INFO o.a.j.JMeter: JMeter  Locale=English (EN)
2020-03-09 23:14:04,672 INFO o.a.j.JMeter: JMeterHome=/usr/local/Cellar/jmeter/5.2.1/libexec
2020-03-09 23:14:04,672 INFO o.a.j.JMeter: user.dir  =/Users/smoneta
2020-03-09 23:14:04,672 INFO o.a.j.JMeter: PWD       =/Users/smoneta
2020-03-09 23:14:04,673 INFO o.a.j.JMeter: IP: 192.168.22.20 Name: santos-ltm.internal.salesforce.com FullName: 192.168.22.20
2020-03-09 23:14:04,676 INFO o.a.j.s.FileServer: Default base='/Users/smoneta'
2020-03-09 23:14:04,679 INFO o.a.j.s.FileServer: Set new base='/Users/smoneta/Desktop/JMETER-TESTS'
2020-03-09 23:14:04,767 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2020-03-09 23:14:04,776 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2020-03-09 23:14:04,780 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2020-03-09 23:14:04,786 INFO o.a.j.s.SaveService: Loading file: /Users/smoneta/Desktop/JMETER-TESTS/KafkaPOC.jmx
2020-03-09 23:14:04,838 INFO o.a.j.JMeter: Creating summariser <summary>
2020-03-09 23:14:04,842 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2020-03-09 23:14:04,842 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-03-09 23:14:04,842 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2020-03-09 23:14:04,846 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2020-03-09 23:14:04,846 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2020-03-09 23:14:05,062 INFO o.a.j.p.j.s.JavaSampler: Created class: co.signal.kafkameter.KafkaProducerSampler. Uses tearDownTest: 
2020-03-09 23:14:05,063 INFO o.a.j.JMeter: Running test (1583806445063)
2020-03-09 23:14:05,086 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Kafka Producer Thread
2020-03-09 23:14:05,086 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Kafka Producer Thread.
2020-03-09 23:14:05,086 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2020-03-09 23:14:05,086 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2020-03-09 23:14:05,090 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2020-03-09 23:14:05,090 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2020-03-09 23:14:05,421 INFO o.a.j.t.JMeterThread: Thread started: Kafka Producer Thread 1-1
2020-03-09 23:14:05,472 INFO c.s.k.KafkaProducerSampler: Setting up SSL properties...
2020-03-09 23:14:05,473 INFO o.a.j.t.JMeterThread: Thread finished: Kafka Producer Thread 1-1
**2020-03-09 23:14:05,473 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[Kafka Producer Thread 1-1,5,main]**
java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer
	at co.signal.kafkameter.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:149) ~[kafkameter-0.2.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:195) ~[ApacheJMeter_java.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) ~[ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.KafkaProducer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 7 more
2020-03-09 23:14:05,477 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-03-09 23:14:05,478 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,5,main]
java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer
	at co.signal.kafkameter.KafkaProducerSampler.teardownTest(KafkaProducerSampler.java:154) ~[kafkameter-0.2.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:299) ~[ApacheJMeter_java.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492) ~[ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2020-03-09 23:14:05,479 INFO o.a.j.r.ResultCollector: Shutdown hook started
2020-03-09 23:14:05,479 INFO o.a.j.r.ResultCollector: Shutdown hook ended
```

Any pointer on what may be the issue?

**Comment by dekideian** [comment]
Hey, I don't see any updates after the date this issue was created. Is this project still maintained? I use a 2.7.0. kafka right now..
