### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by sandrews** [BrightTag/kafkameter#8]
Hi,

I'm getting this NoClassDefFoundError, I packaged and dxtopped the uber jar in lib/ext.. While running I get the followin.g

2015/10/15 01:57:18 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: scala/Tuple2$mcJJ$sp
	at kafka.producer.ProducerConfig.<init>(ProducerConfig.scala:56)
	at co.signal.kafkameter.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:90)
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:188)
	at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.Tuple2$mcJJ$sp
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 6 more

**Comment by codyaray** [comment]
Sounds like there's a version mismatch between your scala version and the Kafka library version. This library currently uses a Kafka client dependency which requires scala 2.8.2. You can see/change this in [pom.xml](https://github.com/BrightTag/kafkameter/blob/master/pom.xml#L77). 

Make sure your versions match and you shouldn't get this issue.

**Comment by sandrews** [comment]
awesome thanx


*Shantha Andrews(215) 272-1034    *

*@shantha_andrews  shantha.andrews@gmail.com <shantha.andrews@gmail.com>*

*https://www.linkedin.com/in/shantha
<https://www.linkedin.com/in/shantha>https://twitter.com/shantha_andrews
<https://twitter.com/shantha_andrews>*
