### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: kafka/serializer/DefaultEncoder Issue in JMeter

### ISSUE THREAD

**Issue by krishnamohanty91** [BrightTag/kafkameter#9]
On running in JMeter I am getting below error. Request to please help with the fix.

2016/05/31 16:32:52 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: kafka/serializer/DefaultEncoder
    at co.signal.kafkameter.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:86)
    at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:188)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:431)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:258)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: kafka.serializer.DefaultEncoder
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 5 more

2016/05/31 16:32:52 INFO  - jmeter.threads.JMeterThread: Thread finished: Thread Group 1-1 
2016/05/31 16:32:52 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2016/05/31 16:32:52 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: kafka/javaapi/producer/Producer
    at co.signal.kafkameter.KafkaProducerSampler.teardownTest(KafkaProducerSampler.java:96)
    at org.apache.jmeter.protocol.java.sampler.JavaSampler.testEnded(JavaSampler.java:287)
    at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:226)
    at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:448)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: kafka.javaapi.producer.Producer
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 5 more

**Comment by codyaray** [comment]
Make sure you're using Kafka 2.8.2-0.8.0 or update the pom.xml to match. Otherwise seems like your classpath might be messed up. How are you building the project?
